version: '3'

services:
    app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        volumes:
            - ./:/app
        ports:
            - "8080:8080"
        depends_on:
            - kafka
        restart: "no"

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        restart: "no"

    kafka:
        image: wurstmeister/kafka:2.12-2.4.0
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "example:32:1"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - zookeeper
        restart: "no"

    kafka_manager:
        image: kafkamanager/kafka-manager
        environment:
            ZK_HOSTS: zookeeper
        ports:
            - "9000:9000"
        restart: "no"

